# Generated by Django 2.1.7 on 2019-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20190529_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
