# Generated by Django 2.1.7 on 2019-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20190623_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_post',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to='static/todo_app/'),
        ),
    ]
